name: CI Pipeliness

on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: create env file
      #   run: |
      #     cd communities/packages/api && \
      #     touch .env && \
      #     echo "API_PORT=4000" > .env && \
      #     echo "API_URL=https://backcommunities.eze.ink" >> .env && \
      #     echo "NODE_ENV=production" >> .env && \
      #     echo "SECRET=WriteYourSecret" >> .env && \
      #     echo "FRONTEND_URL=https://communities.eze.ink" >> .env && \
      #     echo "MONGO_URL=mongodb+srv://eze:nMWN2NG50nSLJrOC@eze-communities.ufwbl4d.mongodb.net/?retryWrites=true&w=majority" >> .env && \
      #     echo "CLOUDINARY_CLOUD_NAME=dyekwrvwe" >> .env && \
      #     echo "CLOUDINARY_API_KEY=981519692274267" >> .env && \
      #     echo "CLOUDINARY_SECRET=EnwDIzzscMxY5SacVWoqUXE0mzw" >> .env && \
      #     echo "MAILGUN_API_KEY=YOUR_MAILGUN_API_KEY" >> .env && \
      #     echo "MAILGUN_DOMAIN=YOUR_MAILGUN_DOMAIN" >> .env

      # - name: create env file landing page 
      #   run: |
      #     cd landing-page && \
      #     touch .env && \
      #     echo "REACT_APP_API_URL=https://backcommunities.eze.ink" > .env && \
      #     echo 'NEXT_PUBLIC_COMMUNITIES_URL="https://communities.eze.ink/"' >> .env && \
      #     echo 'NEXT_PUBLIC_SSO_LOGIN_URL="https://sso.eze.ink/auth/login"' >> .env
      
      - name: Create env file for communities frontend
        run: |
          cd communities/packages/frontend && \
          touch .env && \
          echo "NODE_ENV=production" > .env && \
          echo "GOOGLE_ANALYTICS_ID=G-MD706N8TZV" >> .env && \
          echo "NEXT_API_PRODUCTION_URL=https://backcommunities.eze.ink" >> .env && \
          echo "NEXT_PUBLIC_COMMUNITIES_URL=https://communities.eze.ink" >> .env && \
          echo "NEXT_PUBLIC_SSO_LOGIN_URL=https://sso.eze.ink/auth/login" >> .env && \
          echo "NEXT_PUBLIC_LANDINGPAGE_URL=https://eze.ink" >> .env

      # - name: Create env file for SSO
      #   run: |
      #     cd sso/eze-auth0 && \
      #     touch .env && \
      #     echo "MONGODB_URI=mongodb+srv://eze:mongodb123@cluster0.dbnvshu.mongodb.net/eze_sso?retryWrites=true&w=majority&appName=Cluster0" > .env && \
      #     echo "PORT=3000" >> .env && \
      #     echo "SSO_URL=https://sso.eze.ink" >> .env && \
      #     echo "REDIRECT_ORIGIN=https://eze.ink" >> .env && \
      #     echo "CALLBACK_URL=https://sso.eze.ink/auth/login/callback" >> .env    
      - name: Build Docker image
        run: docker-compose build

      - name: Tag Docker image
        run: docker tag frontend_communities ezekielkaeyros/frontend_eze_staging

      - name: build library image
        run: |
          cd digital-library/frontend && \
          docker build -t ezekielkaeyros/ezelibrary .

      - name: Tag Docker image
        run: docker tag ezelibrary ezekielkaeyros/ezelibrary

      # - name: Tag Docker image
      #   run: docker tag backend_communities ezekielkaeyros/backend_communities_staging

      # - name: Tag Docker image
      #   run: docker tag landing_communities ezekielkaeyros/eze_landing_staging

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ezekielkaeyros/frontend_eze_staging:latest

      - name: Push Docker image
        run: docker push ezekielkaeyros/ezelibrary:latest

      # - name: Push Docker image
      #   run: docker push ezekielkaeyros/backend_communities_staging:latest

      # - name: Push Docker image
      #   run: docker push ezekielkaeyros/eze_landing_staging:latest

      # - name: build sso image
      #   run: |
      #     cd sso/eze-auth0 && \
      #     docker build -t ezekielkaeyros/sso_staging .

      # - name: push sso image
      #   run: docker push ezekielkaeyros/sso_staging:latest

