name: Pipelines Staging

on:
  push:
    branches:
      - main 

jobs:
  checkout-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-repository
        uses: actions/checkout@v3

  create-env-file-api:
    runs-on: ubuntu-latest
    needs: checkout-repository
    steps:
      - name: view the directory
        run: |
          ls 
      - name: Create env file for API backend
        run: |
        
          cd eze_staging/eze_staging/communities/packages/api && \ && \
          touch .env && \
          echo "API_PORT=4000" > .env && \
          echo "API_URL=https://backcommunities.eze.ink" >> .env && \
          echo "NODE_ENV=production" >> .env && \
          echo "SECRET=WriteYourSecret" >> .env && \
          echo "FRONTEND_URL=https://communities.eze.ink" >> .env && \
          echo "MONGO_URL=mongodb+srv://eze:nMWN2NG50nSLJrOC@eze-communities.ufwbl4d.mongodb.net/?retryWrites=true&w=majority" >> .env && \
          echo "CLOUDINARY_CLOUD_NAME=dyekwrvwe" >> .env && \
          echo "CLOUDINARY_API_KEY=981519692274267" >> .env && \
          echo "CLOUDINARY_SECRET=EnwDIzzscMxY5SacVWoqUXE0mzw" >> .env && \
          echo "MAILGUN_API_KEY=YOUR_MAILGUN_API_KEY" >> .env && \
          echo "MAILGUN_DOMAIN=YOUR_MAILGUN_DOMAIN" >> .env

  create-env-file-landing-page:
    runs-on: ubuntu-latest
    needs: checkout-repository
    steps:
      - name: Create env file for landing page 
        run: |
          cd $GITHUB_WORKSPACE/landing-page && \
          touch .env && \
          echo "REACT_APP_API_URL=https://backcommunities.eze.ink" > .env && \
          echo 'NEXT_PUBLIC_COMMUNITIES_URL="https://communities.eze.ink/"' >> .env && \
          echo 'NEXT_PUBLIC_SSO_LOGIN_URL="https://sso.eze.ink/auth/login"' >> .env

  create-env-file-communities-packages:
    runs-on: ubuntu-latest
    needs: checkout-repository
    steps:
      - name: Create env file for communities frontend
        run: |
          cd $GITHUB_WORKSPACE/communities/packages/frontend && \
          touch .env && \
          echo "NODE_ENV=http://localhost:4000" > .env && \
          echo "GOOGLE_ANALYTICS_ID=G-MD706N8TZV" >> .env && \
          echo "NEXT_API_PRODUCTION_URL=https://backcommunities.eze.ink" >> .env && \
          echo "NEXT_PUBLIC_COMMUNITIES_URL=https://communities.eze.ink" >> .env && \
          echo "NEXT_PUBLIC_SSO_LOGIN_URL=https://sso.eze.ink/auth/login" >> .env && \
          echo "NEXT_PUBLIC_LANDINGPAGE_URL=https://eze.ink" >> .env

  create-env-file-sso:
    runs-on: ubuntu-latest
    needs: checkout-repository
    steps:
      - name: Create env file for SSO
        run: |
          cd $GITHUB_WORKSPACE/sso/eze-auth0 && \
          touch .env && \
          echo "MONGODB_URI=mongodb+srv://eze:mongodb123@cluster0.dbnvshu.mongodb.net/eze_sso?retryWrites=true&w=majority&appName=Cluster0" > .env && \
          echo "PORT=3000" >> .env && \
          echo "SSO_URL=https://sso.eze.ink" >> .env && \
          echo "REDIRECT_ORIGIN=https://eze.ink" >> .env && \
          echo "CALLBACK_URL=https://sso.eze.ink/auth/login/callback" >> .env

  login-dockerhub:
    runs-on: ubuntu-latest
    needs: [create-env-file-api, create-env-file-landing-page, create-env-file-communities-packages, create-env-file-sso]
    steps:
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

  build-and-push-frontend-image:
    runs-on: ubuntu-latest
    needs: login-dockerhub
    steps:
      - name: Build frontend Docker image
        run: docker build -
